resolver: lts-11.7
flags: {}
packages:
- '.'
- location:
    git: https://github.com/hansroland/recursion-schemes-helpers
    commit: 00b669d3ede03e67bdae3230456d6036ce9f660d
  extra-dep: true

extra-deps: 
- recursion-schemes-ext-1.0.0.3